# Generated by Django 4.0.4 on 2022-08-04 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_alter_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='uploaddate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
